import './globals.css'
import type { Metadata } from 'next'
import CssBaseline from '@mui/material/CssBaseline'

import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <CssBaseline />
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
